### ISSUE TITLE
Error: no suitable image found.

### ISSUE THREAD

**Issue by yangtoude** [apollographql/apollo-tutorial-kit#20]
Hi, i encounter this error after 'npm install --save sequelize sqlite lodash':
`Error: dlopen(/Users/qijiaona/var/www/apollo-tutorial-kit/node_modules/sqlite3/lib/binding/node-v47-darwin-x64/node_sqlite3.node, 1): no suitable image found.  Did find:
    /Users/qijiaona/var/www/apollo-tutorial-kit/node_modules/sqlite3/lib/binding/node-v47-darwin-x64/node_sqlite3.node: truncated mach-o error: segment __TEXT extends to 1306624 which is past end of file 339456
    at Error (native)
    at Object.Module._extensions..node (module.js:422:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/qijiaona/var/www/apollo-tutorial-kit/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:397:26)
    at Module._extensions..js (module.js:404:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/qijiaona/var/www/apollo-tutorial-kit/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at new ConnectionManager (/Users/qijiaona/var/www/apollo-tutorial-kit/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:22:16)
    at new SqliteDialect (/Users/qijiaona/var/www/apollo-tutorial-kit/node_modules/sequelize/lib/dialects/sqlite/index.js:12:28)`

**Comment by helfer** [comment]
@yangtoude Which version of node are you on? Can you try running `npm rebuild sqlite3`?
